# Generated by Django 4.2.14 on 2024-08-01 14:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsCategoryModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=200)),
                ('update_date', models.TimeField(auto_now=True)),
                ('pub_date', models.TimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NewsModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('article', models.TextField()),
                ('permit', models.BooleanField(default=False)),
                ('trending_news', models.BooleanField(default=False)),
                ('featured_news', models.BooleanField(default=False)),
                ('breaking_news', models.BooleanField(default=False)),
                ('pub_date', models.TimeField(auto_now_add=True)),
                ('update_date', models.TimeField(auto_now=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_article.newscategorymodel')),
            ],
        ),
    ]
