# Generated by Django 4.2.14 on 2024-08-01 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_article', '0002_newsmodel_title_alter_newscategorymodel_pub_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsmodel',
            name='description',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
